### PR TITLE
Add feature to enable TLS on Cloud

### PR DESCRIPTION
**Pull request by johandry**
* Add TLS/SSL port to Docker on AWS and Azure
* Add TLS variable to UI Docker container on AWS and Azure
* Create shared volume for UI and Server to share TLS certificate on AWS and Azure
* Removing parameter `AiUnlimitedUiPort` on AWS, UI port is not a user choice, it's port `80`
* Add port 443 to same places where port 80 is, on AWS

Pending to do in other PR:
* Do previous changes on other Azure files and big-template
* Removing parameter `{3}` on Azure, UI port is not a user choice, it's port `80`
* Add port 443 to same places where port 80 is, on Azure and big-template

### CODE REVIEW

**Comment by alicia-td** [comment]
@johandry, with these changes, I would have to port them to the full deployment templates as well. I'll start on it next week.

**Review by cloud-work535 — APPROVED** [review]
lgtm, able to deploy AWS deployment

**Comment by cloud-work535** [comment]
Able to deploy the template and configure it with tls.
Screenshot 2024-11-05 at 4 43 14 PM

AWS Compute engine deployment:
Screenshot 2024-11-05 at 4 47 11 PM

**Comment by johandry** [comment]
It is pending to do the same changes on Azure and the Big template. This will be done in other PR to not block the UAT on AWS

**Review by alicia-td — APPROVED** [review]

**Pull request merged**
